server:
  port: 8080
  session-timeout: 30
  tomcat:
    max-threads: 0
    uri-encoding: UTF-8

spring:
  datasource:
#    url: jdbc:oracle:thin:@10.20.149.85:1521:ocnauto
#    username: root
#    password: root
#    driver-class-name: oracle.jdbc.driver.OracleDriver

    url: jdbc:postgresql://localhost/vendor
    username: postgres
    password: 23420800
    driver-class-name: org.postgresql.Driver

    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true

mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml

logging:
#  path: /var/log/
  file: automat.log
  level:
    root: ERROR
    com:
      unipresident:
        automat:
          mapper:
            DEBUG

system:
  appkey: 1234567890
  secret: qwertyuiop
  version: V1
  interval: 300000